# Generated by Django 5.0.4 on 2024-04-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporthub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
