# Generated by Django 5.0.6 on 2024-08-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporthub', '0004_remove_post_duration_post_gpx_data_post_time_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avg_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='avg_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='cadence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='max_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
