# Generated by Django 5.0.6 on 2024-08-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporthub', '0005_post_avg_heart_rate_post_avg_speed_post_cadence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avg_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='max_power',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
